Repository ferreira-tb/tauri-plugin-prevent-default, pull requests merged in 2024-12, with the labels that each got.

#16 fix: downgrade MSRV to 1.77.2 to support Windows 7
  Cargo.toml
Labels: bug

#17 BREAKING CHANGE: drop `ahash` support
  Cargo.toml
  README.md
  src/lib.rs
  src/state.rs
Labels: BREAKING CHANGE

#20 fix: check target os
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/platform/mod.rs
  src/platform/windows.rs
Labels: bug

#21 fix: typo in Cargo.toml deps example
  README.md
Labels: documentation
